/**
 * Which subjects have a long-form article — GENERATED by
 * tools/build-article-index.js. Do not edit by hand; `npm test` fails on drift.
 *
 * A view needs this to decide whether to offer a "full article" control without
 * first downloading the articles themselves, which are large and deliberately
 * fetched only when a reader asks for one.
 */

const LQ_ARTICLE_IDS = {
  "prophets": [
    "adam",
    "alyasa",
    "ayyub",
    "dawud",
    "dhulkifl",
    "harun",
    "hud",
    "ibrahim",
    "idris",
    "ilyas",
    "isa",
    "ishaq",
    "ismail",
    "lut",
    "muhammad",
    "musa",
    "nuh",
    "salih",
    "shuayb",
    "sulayman",
    "yahya",
    "yaqub",
    "yunus",
    "yusuf",
    "zakariya"
  ],
  "sahaba": [
    "abdullah_ibn_abbas",
    "abdullah_ibn_masud",
    "abdur_rahman_ibn_awf",
    "abu_bakr_as_siddiq",
    "abu_hurayrah",
    "abu_ubaydah_ibn_al_jarrah",
    "aishah_bint_abi_bakr",
    "ali_ibn_abi_talib",
    "ammar_ibn_yasir",
    "asma_bint_abi_bakr",
    "az_zubayr_ibn_al_awwam",
    "bilal_ibn_rabah",
    "fatimah_az_zahra",
    "hamza_ibn_abd_al_muttalib",
    "jafar_ibn_abi_talib",
    "khadijah_bint_khuwaylid",
    "khalid_ibn_al_walid",
    "muadh_ibn_jabal",
    "musab_ibn_umayr",
    "nusaybah_bint_kab_umm_umarah",
    "sad_ibn_abi_waqqas",
    "said_ibn_zayd",
    "salman_al_farsi",
    "sumayyah_bint_khayyat",
    "talha_ibn_ubaydillah",
    "umar_ibn_al_khattab",
    "umm_ayman_barakah",
    "umm_salamah",
    "uthman_ibn_affan",
    "zayd_ibn_harithah"
  ],
  "tadabbur": [
    "103:1-3",
    "13:28",
    "14:7",
    "17:23-24",
    "24:35",
    "25:63",
    "29:69",
    "2:152",
    "2:186",
    "2:216",
    "2:255",
    "2:286",
    "33:35",
    "39:53",
    "3:159",
    "3:26-27",
    "55:60",
    "57:20",
    "59:21",
    "64:15",
    "94:5-6",
    "9:40"
  ]
};

if (typeof module !== 'undefined' && module.exports) module.exports = { LQ_ARTICLE_IDS };
