exec(open('/var/www/html/learnquranbd/all-language-quran/tools/wip/round11/audit/12_16/rewrite.py').read().split('R = [')[0])
R = [
("Read carefully, the principle is narrow",
 "Read carefully, the principle is narrow. It says tears are not proof of truth. It does not say they are proof of a lie, and nothing in the verse makes weeping suspect in itself. The brothers' tears are exposed by what the rest of the surah reveals about that day, not by the fact that they wept. Nor did they move the father to accept the story, as 12:18 shows; his reply belongs to that verse and its article.",
 "মনোযোগ দিয়ে পড়লে নীতিটা খুব সীমিত। এর কথা শুধু এটুকু: কান্না সত্যের প্রমাণ নয়। কান্না মিথ্যার প্রমাণ, এমন কথা এতে নেই। কাঁদাটাই সন্দেহের বিষয়, আয়াতেও এমন কোনো ইঙ্গিত নেই। ভাইদের কান্নার আসল রূপ বেরিয়ে আসে সেদিনের ব্যাপারে বাকি সূরা যা খুলে বলে তা দিয়ে, তারা কেঁদেছিল বলে নয়। আর এই কান্না দেখে বাবা গল্পটা মেনেও নেননি, ১২:১৮ আয়াতেই তা স্পষ্ট। তাঁর জবাব ওই আয়াত আর তার প্রবন্ধের বিষয়।"),
("Elsewhere the Quran speaks of weeping",
 "Elsewhere the Quran speaks of weeping it vouches for. 5:83 describes people whose eyes overflow when they hear what was revealed to the Messenger, because of the truth they have recognised. 9:92 speaks of men who asked the Prophet ﷺ for mounts for the expedition and turned back in tears, grieved that they had nothing to spend. 17:109 shows those given knowledge falling on their faces weeping, growing in humility. And 53:43 lays the ground beneath it all: it is He who makes people laugh and weep.",
 "কুরআনের অন্য জায়গায় এমন কান্নার কথা আছে, যার সাক্ষ্য কুরআন নিজেই দেয়। ৫:৮৩ আয়াতে এমন মানুষের কথা, রাসূলের উপর নাযিল হওয়া বাণী শুনলে যাদের চোখ অশ্রুতে ভরে যায়, কারণ তারা সত্যকে চিনে ফেলেছে। ৯:৯২ আয়াতে সেই মানুষগুলো, যারা অভিযানে যাওয়ার বাহন চাইতে নবী ﷺ-এর কাছে এসেছিল। বাহন না পেয়ে তারা ফিরে গেল অশ্রুভরা চোখে, খরচ করার মতো কিছু নেই বলে দুঃখে। ১৭:১০৯ আয়াতে জ্ঞান পাওয়া মানুষেরা কাঁদতে কাঁদতে সিজদায় লুটিয়ে পড়ে, তাদের বিনয় বাড়ে। আর ৫৩:৪৩ আয়াত গোড়ার কথাটা বলে দেয়: তিনিই হাসান, তিনিই কাঁদান।"),
("As-Sa'di reads the timing differently",
 "As-Sa'di reads the timing differently. They came at nightfall, he says, so that their return would be later than their habit, and so that their weeping would be evidence for them and a sign that they were truthful. The difference is worth keeping. Al-Qurtubi and al-Baghawi look at what the dark does for the one who lies: it hides a face that might give him away. As-Sa'di looks at what lateness and tears do for the story: they fit the account of a disaster. Both see the hour as chosen.",
 "সাদী সময়টা পড়েন অন্যভাবে। তাঁর মতে, তারা রাতের শুরুতে এসেছিল যেন ফেরাটা তাদের অভ্যাসের চেয়ে দেরিতে হয়, আর কান্নাটা হয় তাদের পক্ষে প্রমাণ, তারা যে সত্য বলছে তার আলামত। পার্থক্যটা রেখে দেওয়ার মতো। কুরতুবী আর বাগাভী দেখেন, মিথ্যাবাদীর জন্য অন্ধকার কী করে: যে চেহারা তাকে ধরিয়ে দিতে পারত, তা ঢেকে দেয়। সাদী দেখেন, দেরি আর কান্না গল্পের জন্য কী করে: দুটোই একটা দুর্ঘটনার বিবরণের সঙ্গে খাপ খেয়ে যায়। তবে সময়টা যে ভেবেচিন্তে বেছে নেওয়া, দুই পক্ষই তা মানেন।"),
("The chain in the narration",
 "The chain in the narration can be broken at any link, and the earlier the cheaper. A small untruth told to cover a mistake at work, a missed payment or a promise broken to a child soon asks for a second to hold it up. The moment you notice that second request is the moment to stop. Say what happened, accept what follows, and ask Allah's forgiveness. The brothers' concealment ran for years before the confession of 12:97; nobody reading the surah has to wait as long.",
 "হাদীসে যে শিকলের কথা, তার যেকোনো কড়ায় তা ভাঙা যায়, আর যত আগে ভাঙা যায় তত কম দাম দিতে হয়। অফিসের একটা ভুল, সময়মতো না দেওয়া কোনো পাওনা, সন্তানকে দেওয়া কথা রাখতে না পারা, এসব ঢাকতে বলা ছোট্ট একটা অসত্য খুব শিগগির তাকে টিকিয়ে রাখার জন্য আরেকটা অসত্য চাইবে। দ্বিতীয় সেই চাহিদা যখন টের পাবেন, থামার সময় তখনই। যা ঘটেছে বলে দিন, তার ফল মেনে নিন, আল্লাহর কাছে মাফ চান। ১২:৯৭ আয়াতের স্বীকারোক্তির আগে ভাইদের লুকোচুরি চলেছিল বহু বছর। সূরার পাঠকের এত দিন অপেক্ষা করার দরকার নেই।"),
("One misuse must be ruled out",
 "One misuse must be ruled out. This verse is no licence to doubt the grief of a widow, a child in trouble or a colleague who breaks down. The Quran told us what these particular tears were covering, and nothing about anyone else's. Where a claim must be decided, by a judge, an arbiter or a parent between two children, decide on what can be shown, as al-Qurtubi's principle requires, and let tears move you to gentleness, not to a verdict. Everywhere else, meet weeping with mercy.",
 "একটা অপব্যবহার শুরুতেই নাকচ করতে হবে। কোনো বিধবার শোক, বিপদে পড়া কোনো শিশুর কান্না কিংবা ভেঙে পড়া কোনো সহকর্মীর চোখের পানিকে সন্দেহ করার অনুমতি এ আয়াত দেয় না। এই নির্দিষ্ট কান্না কী ঢেকে রাখছিল, কুরআন তা জানিয়েছে, অন্য কারো কান্না নিয়ে কিছুই জানায়নি। যেখানে কোনো দাবির ফয়সালা করতেই হয়, বিচারক, সালিশ বা দুই সন্তানের মাঝে দাঁড়ানো বাবা-মা হিসেবে, সেখানে কুরতুবীর নীতি অনুযায়ী যা দেখানো যায় তার ভিত্তিতে ফয়সালা করুন। কান্না আপনাকে নরম করুক, রায় যেন না বদলায়। বাকি সব জায়গায় কান্নার সামনে মমতা নিয়ে দাঁড়ান।"),
("Questions to carry from the four words",
 "Questions to carry from the four words. When I last owed someone an explanation, did I choose the hour and the setting so that I would be harder to read? Have my tears ever argued a case my words could not honestly make? Which wrong of mine has already needed a second concealment? When someone weeps in front of me, is my first movement mercy or suspicion? And is there a confession I could make tomorrow, in daylight, to the person I wronged?",
 "এই ৪টি শব্দ থেকে সঙ্গে নেওয়ার মতো কিছু প্রশ্ন। শেষবার যখন কাউকে কৈফিয়ত দিতে হয়েছিল, সময় আর পরিবেশটা কি এমনভাবে বেছেছিলাম যাতে আমার চেহারা পড়া কঠিন হয়? আমার চোখের পানি কি কখনো এমন দাবি প্রমাণ করতে নেমেছে, যা আমার কথা সৎভাবে পারত না? আমার কোন অন্যায় ঢাকতে এর মধ্যেই দ্বিতীয় আরেকটা লুকোচুরি লেগেছে? কেউ সামনে কাঁদলে আমার মনে প্রথমে জাগে মমতা, নাকি সন্দেহ? আর যার প্রতি অন্যায় করেছি, তার কাছে কাল দিনের আলোয় গিয়ে স্বীকার করার মতো কোনো কথা কি আমার আছে?"),
]
for r in R:
    rep(*r)
open(p, 'w', encoding='utf8').write(s)
print('ok')
